pipeline:
  build:
    image: golang:alpine
    commands:
      - apk --no-cache add git
      - GOARCH=amd64 GOOS=linux go build artibot.go
    when:
      event: 
        - push
        - pull_request
